# Generated by Django 3.2.9 on 2022-03-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('price_beef_kilo', models.CharField(max_length=100)),
                ('price_rice_kilo', models.CharField(max_length=100)),
                ('price_coffee_kilo', models.CharField(max_length=100)),
                ('inflation_rate', models.CharField(max_length=100)),
            ],
        ),
    ]
